### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by timzhang642** [jessemelpolio/non-stationary_texture_syn#5]
Hi,

I'm running the code using Linux with a Nvidia P100 card (16GB memory) and Pytorch 0.4. It's okay to train small images that's around the size 256x256 to generate 512x512. However, when I train using an image that's 500x500, it threw me an out-of-memory error below during validation stage. I think 16GB should be sufficient for this image size, do you happen to have any idea why this happens? 

>Traceback (most recent call last):
  File "train.py", line 66, in <module>
    test_func(opt, webpage, epoch=str(epoch))
  File "/home/yuzhang/non-stationary_texture_syn/test_function.py", line 48, in test_func
    model.test()
  File "/home/yuzhang/non-stationary_texture_syn/models/test_model.py", line 38, in test
    self.fake_B = self.netG.forward(self.real_A)
  File "/home/yuzhang/non-stationary_texture_syn/models/networks.py", line 221, in forward
    return self.model(input)
  File "/home/yuzhang/anaconda3/envs/pytorch_3.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yuzhang/anaconda3/envs/pytorch_3.5/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/yuzhang/anaconda3/envs/pytorch_3.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yuzhang/anaconda3/envs/pytorch_3.5/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by jessemelpolio** [comment]
Hi, I open the testing function during training. Normally, the testing function will load the image with its original size. Say you have an image over 1000x1000, then the output will be 2000x2000. Therefore, it might take up a lot of GPU space. I think this could be a cause leading to your problem. You can try to comment this line: `test_func(opt, webpage, epoch=str(epoch))` in train.py to avoid the testing process during training or try a bit smaller image. You can also try to modify the options about loading image to a smaller size rather than  the original size (in test_function.py).

**Comment by timzhang642** [comment]
Thanks for the response! Turned out I need to change the volatile flag to 

> with torch.no_grad():
self.real_A = Variable(self.fake_B.data)
self.fake_B = self.netG.forward(self.real_A)

because the volatile flag is deprecated in Torch 0.4.0. After this change, I was able to generate 2400x2400 image using a 1080 card. 

Now I wonder how much extra juice can we squeeze out of it. Do you think it's possible to generate 4K image?

**Comment by jessemelpolio** [comment]
I'm not quite sure about space usage. My experiments are mostly conducted on one Titan Xp card with 12GB GPU memories. My most training images are around 800~.
